# Generated by Django 5.0.6 on 2024-07-15 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=500, primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=500)),
                ('ue', models.CharField(max_length=500)),
                ('semestre', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('file', models.FileField(unique=True, upload_to='document')),
            ],
        ),
    ]
