# Generated by Django 5.0.6 on 2024-06-29 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('semestre', models.IntegerField()),
            ],
        ),
    ]
