# Generated by Django 5.0.6 on 2024-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculte',
            name='faculte',
            field=models.CharField(default='FaST', max_length=500),
        ),
    ]
