# Generated by Django 5.0.6 on 2024-07-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faculte_faculte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculte',
            name='faculte',
            field=models.CharField(default='', max_length=500),
        ),
    ]
